/*
Deployment script for SAM5DB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "SAM5DB"
:setvar DefaultFilePrefix "SAM5DB"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SAM\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SAM\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
print '$$$-predeployment-start-do-not-change-this-line-$$$'



print '$$$-predeployment-end-do-not-change-this-line-$$$'
GO

GO
PRINT N'Dropping [biz].[fk_position_request_request]...';


GO
ALTER TABLE [biz].[position_request] DROP CONSTRAINT [fk_position_request_request];


GO
PRINT N'Dropping [person].[fk_person_relation_request_request]...';


GO
ALTER TABLE [person].[person_relation_request] DROP CONSTRAINT [fk_person_relation_request_request];


GO
PRINT N'Dropping [core].[fk_hierarchy_request_request]...';


GO
ALTER TABLE [core].[hierarchy_request] DROP CONSTRAINT [fk_hierarchy_request_request];


GO
PRINT N'Dropping [stock].[fk_issue_request_request]...';


GO
ALTER TABLE [stock].[issue_request] DROP CONSTRAINT [fk_issue_request_request];


GO
PRINT N'Dropping [biz].[fk_board_request_request]...';


GO
ALTER TABLE [biz].[board_request] DROP CONSTRAINT [fk_board_request_request];


GO
PRINT N'Dropping [req].[fk_request_document]...';


GO
ALTER TABLE [req].[request] DROP CONSTRAINT [fk_request_document];


GO
PRINT N'Dropping [req].[fk_request_data_operation_type]...';


GO
ALTER TABLE [req].[request] DROP CONSTRAINT [fk_request_data_operation_type];


GO
PRINT N'Dropping [req].[fk_request_request_type]...';


GO
ALTER TABLE [req].[request] DROP CONSTRAINT [fk_request_request_type];


GO
PRINT N'Dropping [req].[fk_request_document_history]...';


GO
ALTER TABLE [req].[request] DROP CONSTRAINT [fk_request_document_history];


GO
PRINT N'Dropping [biz].[fk_company_request_request]...';


GO
ALTER TABLE [biz].[company_request] DROP CONSTRAINT [fk_company_request_request];


GO
PRINT N'Dropping [req].[fk_request_transition_request]...';


GO
ALTER TABLE [req].[request_transition] DROP CONSTRAINT [fk_request_transition_request];


GO
PRINT N'Dropping [biz].[fk_subdivision_request_request]...';


GO
ALTER TABLE [biz].[subdivision_request] DROP CONSTRAINT [fk_subdivision_request_request];


GO
PRINT N'Dropping [stock].[fk_deal_request_request]...';


GO
ALTER TABLE [stock].[deal_request] DROP CONSTRAINT [fk_deal_request_request];


GO
PRINT N'Dropping [person].[fk_person_request_request]...';


GO
ALTER TABLE [person].[person_request] DROP CONSTRAINT [fk_person_request_request];


GO
PRINT N'Dropping [biz].[fk_board_request_member_position]...';


GO
ALTER TABLE [biz].[board_request_member] DROP CONSTRAINT [fk_board_request_member_position];


GO
PRINT N'Starting rebuilding table [req].[request]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [req].[tmp_ms_xx_request] (
    [id]                     INT            IDENTITY (1, 1) NOT NULL,
    [state]                  SMALLINT       NOT NULL,
    [name]                   NVARCHAR (256) NULL,
    [request_type_id]        INT            NOT NULL,
    [author_id]              INT            NOT NULL,
    [data_operation_type_id] INT            NOT NULL,
    [document_type_id]       INT            NULL,
    [document_id]            INT            NULL,
    [document_hid]           INT            NULL,
    [copy_document_type_id]  INT            NULL,
    [copy_document_id]       INT            NULL,
    [copy_document_hid]      INT            NULL,
    [document_name]          NVARCHAR (256) NULL,
    [request_data_id]        INT            NULL,
    [relevance_date]         DATE           NULL,
    [process_id]             INT            NULL,
    [comments_history]       NVARCHAR (MAX) NULL,
    [modified_by]            INT            NOT NULL,
    [modified_date]          DATETIME2 (7)  NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_pk_request1] PRIMARY KEY CLUSTERED ([id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [req].[request])
    BEGIN
        SET IDENTITY_INSERT [req].[tmp_ms_xx_request] ON;
        INSERT INTO [req].[tmp_ms_xx_request] ([id], [state], [name], [request_type_id], [author_id], [data_operation_type_id], [document_type_id], [document_id], [document_hid], [document_name], [request_data_id], [relevance_date], [process_id], [comments_history], [modified_by], [modified_date])
        SELECT   [id],
                 [state],
                 [name],
                 [request_type_id],
                 [author_id],
                 [data_operation_type_id],
                 [document_type_id],
                 [document_id],
                 [document_hid],
                 [document_name],
                 [request_data_id],
                 [relevance_date],
                 [process_id],
                 [comments_history],
                 [modified_by],
                 [modified_date]
        FROM     [req].[request]
        ORDER BY [id] ASC;
        SET IDENTITY_INSERT [req].[tmp_ms_xx_request] OFF;
    END

DROP TABLE [req].[request];

EXECUTE sp_rename N'[req].[tmp_ms_xx_request]', N'request';

EXECUTE sp_rename N'[req].[tmp_ms_xx_constraint_pk_request1]', N'pk_request', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [biz].[fk_position_request_request]...';


GO
ALTER TABLE [biz].[position_request] WITH NOCHECK
    ADD CONSTRAINT [fk_position_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [person].[fk_person_relation_request_request]...';


GO
ALTER TABLE [person].[person_relation_request] WITH NOCHECK
    ADD CONSTRAINT [fk_person_relation_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [core].[fk_hierarchy_request_request]...';


GO
ALTER TABLE [core].[hierarchy_request] WITH NOCHECK
    ADD CONSTRAINT [fk_hierarchy_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [stock].[fk_issue_request_request]...';


GO
ALTER TABLE [stock].[issue_request] WITH NOCHECK
    ADD CONSTRAINT [fk_issue_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [biz].[fk_board_request_request]...';


GO
ALTER TABLE [biz].[board_request] WITH NOCHECK
    ADD CONSTRAINT [fk_board_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [req].[fk_request_document]...';


GO
ALTER TABLE [req].[request] WITH NOCHECK
    ADD CONSTRAINT [fk_request_document] FOREIGN KEY ([document_type_id], [document_id]) REFERENCES [core].[document] ([document_type_id], [id]) ON DELETE SET NULL;


GO
PRINT N'Creating [req].[fk_request_data_operation_type]...';


GO
ALTER TABLE [req].[request] WITH NOCHECK
    ADD CONSTRAINT [fk_request_data_operation_type] FOREIGN KEY ([data_operation_type_id]) REFERENCES [metadata].[data_operation_type] ([id]);


GO
PRINT N'Creating [req].[fk_request_request_type]...';


GO
ALTER TABLE [req].[request] WITH NOCHECK
    ADD CONSTRAINT [fk_request_request_type] FOREIGN KEY ([request_type_id]) REFERENCES [metadata].[request_type] ([id]);


GO
PRINT N'Creating [req].[fk_request_document_history]...';


GO
ALTER TABLE [req].[request] WITH NOCHECK
    ADD CONSTRAINT [fk_request_document_history] FOREIGN KEY ([document_type_id], [document_hid]) REFERENCES [core].[document_history] ([document_type_id], [hid]);


GO
PRINT N'Creating [biz].[fk_company_request_request]...';


GO
ALTER TABLE [biz].[company_request] WITH NOCHECK
    ADD CONSTRAINT [fk_company_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [req].[fk_request_transition_request]...';


GO
ALTER TABLE [req].[request_transition] WITH NOCHECK
    ADD CONSTRAINT [fk_request_transition_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [biz].[fk_subdivision_request_request]...';


GO
ALTER TABLE [biz].[subdivision_request] WITH NOCHECK
    ADD CONSTRAINT [fk_subdivision_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [stock].[fk_deal_request_request]...';


GO
ALTER TABLE [stock].[deal_request] WITH NOCHECK
    ADD CONSTRAINT [fk_deal_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [person].[fk_person_request_request]...';


GO
ALTER TABLE [person].[person_request] WITH NOCHECK
    ADD CONSTRAINT [fk_person_request_request] FOREIGN KEY ([request_id]) REFERENCES [req].[request] ([id]);


GO
PRINT N'Creating [biz].[fk_board_request_member_position]...';


GO
ALTER TABLE [biz].[board_request_member] WITH NOCHECK
    ADD CONSTRAINT [fk_board_request_member_position] FOREIGN KEY ([position_id]) REFERENCES [biz].[position] ([id]);


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
print '$$$-postdeployment-start-do-not-change-this-line-$$$'


print '$$$-postdeployment-end-do-not-change-this-line-$$$'
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [biz].[position_request] WITH CHECK CHECK CONSTRAINT [fk_position_request_request];

ALTER TABLE [person].[person_relation_request] WITH CHECK CHECK CONSTRAINT [fk_person_relation_request_request];

ALTER TABLE [core].[hierarchy_request] WITH CHECK CHECK CONSTRAINT [fk_hierarchy_request_request];

ALTER TABLE [stock].[issue_request] WITH CHECK CHECK CONSTRAINT [fk_issue_request_request];

ALTER TABLE [biz].[board_request] WITH CHECK CHECK CONSTRAINT [fk_board_request_request];

ALTER TABLE [req].[request] WITH CHECK CHECK CONSTRAINT [fk_request_document];

ALTER TABLE [req].[request] WITH CHECK CHECK CONSTRAINT [fk_request_data_operation_type];

ALTER TABLE [req].[request] WITH CHECK CHECK CONSTRAINT [fk_request_request_type];

ALTER TABLE [req].[request] WITH CHECK CHECK CONSTRAINT [fk_request_document_history];

ALTER TABLE [biz].[company_request] WITH CHECK CHECK CONSTRAINT [fk_company_request_request];

ALTER TABLE [req].[request_transition] WITH CHECK CHECK CONSTRAINT [fk_request_transition_request];

ALTER TABLE [biz].[subdivision_request] WITH CHECK CHECK CONSTRAINT [fk_subdivision_request_request];

ALTER TABLE [stock].[deal_request] WITH CHECK CHECK CONSTRAINT [fk_deal_request_request];

ALTER TABLE [person].[person_request] WITH CHECK CHECK CONSTRAINT [fk_person_request_request];

ALTER TABLE [biz].[board_request_member] WITH CHECK CHECK CONSTRAINT [fk_board_request_member_position];


GO
PRINT N'Update complete.';


GO

