/*
Deployment script for SAM5DB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "SAM5DB"
:setvar DefaultFilePrefix "SAM5DB"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SAM\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SAM\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
print '$$$-predeployment-start-do-not-change-this-line-$$$'



print '$$$-predeployment-end-do-not-change-this-line-$$$'
GO

GO
PRINT N'Dropping [sec].[fk_user_access_right_access_right]...';


GO
ALTER TABLE [sec].[user_access_right] DROP CONSTRAINT [fk_user_access_right_access_right];


GO
PRINT N'Dropping [sec].[fk_user_access_right_user]...';


GO
ALTER TABLE [sec].[user_access_right] DROP CONSTRAINT [fk_user_access_right_user];


GO
/*
The column [sec].[user_access_right].[access_right_id] is being dropped, data loss could occur.

The column [sec].[user_access_right].[access_right_code] on table [sec].[user_access_right] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'Starting rebuilding table [sec].[user_access_right]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [sec].[tmp_ms_xx_user_access_right] (
    [user_id]           INT           NOT NULL,
    [access_right_code] VARCHAR (128) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_pk_user_access_right1] PRIMARY KEY CLUSTERED ([user_id] ASC, [access_right_code] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [sec].[user_access_right])
    BEGIN
        INSERT INTO [sec].[tmp_ms_xx_user_access_right] ([user_id])
        SELECT   [user_id]
        FROM     [sec].[user_access_right]
        ORDER BY [user_id] ASC;
    END

DROP TABLE [sec].[user_access_right];

EXECUTE sp_rename N'[sec].[tmp_ms_xx_user_access_right]', N'user_access_right';

EXECUTE sp_rename N'[sec].[tmp_ms_xx_constraint_pk_user_access_right1]', N'pk_user_access_right', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [sec].[fk_user_access_right_access_right]...';


GO
ALTER TABLE [sec].[user_access_right] WITH NOCHECK
    ADD CONSTRAINT [fk_user_access_right_access_right] FOREIGN KEY ([access_right_code]) REFERENCES [sec].[access_right] ([code]);


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
print '$$$-postdeployment-start-do-not-change-this-line-$$$'


print '$$$-postdeployment-end-do-not-change-this-line-$$$'
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [sec].[user_access_right] WITH CHECK CHECK CONSTRAINT [fk_user_access_right_access_right];


GO
PRINT N'Update complete.';


GO
